---
- name: install pip3
  ansible.builtin.apt:
    update_cache: yes
    package:
      - python3-pip
    state: present
  tags:
    - pythonpkgs

- name: upgrade pip itself
  ansible.builtin.pip:
    state: latest
    name: pip
    umask: '0022'
  tags:
    - pythonpkgs

- name: add python3 packages
  ansible.builtin.pip:
    state: latest
    name: "{{ pypi_modules }}"
    umask: '0022'
  tags:
    - pythonpkgs
