---
- name: install pip3
  ansible.builtin.apt:
    update_cache: yes
    package:
      - python3-pip
    state: present
  tags:
    - pythonpkgs

- name: add python3 packages
  ansible.builtin.pip:
    state: present
    name: "{{ pypi_modules }}"
    umask: 0022
  tags:
    - pythonpkgs
